
[profiles]

[profiles.cat]

[profiles.cat.info]
auth_server_name = ""

[profiles.cow]

[profiles.cow.info]
auth_server_name = "farm"

[profiles.cow.token_payload]
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImNvdyIsImlhdCI6MTYwNTU1MzI2MH0.lRhv60Z5iN0w1g3uwDDi-cNAI4-qLIFkBCe-2__PSVo"
refresh_token = "refresh1"
token_auth_server_name = "Bearer"

[profiles.default]

[profiles.default.info]
auth_server_name = ""

[profiles.default.token_payload]
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImRlZmF1bHQiLCJpYXQiOjE2MDU1NTMyNjB9.vBYtPsolKPa_KTbfiVrOAqV9s_-oXMPHK59zyj41g0Y"
refresh_token = "refresh2"
token_auth_server_name = "Bearer"

[profiles.dog]

[profiles.dog.info]
auth_server_name = "home"

[profiles.dog.token_payload]
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImRvZyIsImlhdCI6MTYwNTU1MzI2MH0.hTK7lzCF5VZAqsJBTyzacm76PSFeuiKi9vAwb7lw6DE"
refresh_token = "refresh3"
token_auth_server_name = "Bearer"
